---
name: sync

on:
  workflow_dispatch:

permissions:
  contents: "write"
  pull-requests: "write"

jobs:
  updatecli:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Updatecli in the runner
        uses: updatecli/updatecli-action@v2

      - name: Run Updatecli in apply mode
        run: "updatecli apply --config ./updatecli.d"
        env:
          DOCKER_USERNAME: "${{ secrets.DOCKER_USERNAME }}"
          DOCKER_PASSWORD: "${{ secrets.DOCKER_PASSWORD }}"

      - name: GIT commit and push all changed files
        run: |
          git config --global user.name  "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "${{ env.CI_COMMIT_EMAIL }}"
          git diff --exit-code || git commit -am "${{ env.CI_COMMIT_MESSAGE }}"
          git pull --rebase
          git push
        env:
          CI_COMMIT_MESSAGE: Continuous Integration Build Artifacts
          CI_COMMIT_AUTHOR: gitops
          CI_COMMIT_EMAIL: gitops@myspotontheweb.com
